
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://irwoefmbkcozwbgpfxxz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlyd29lZm1ia2NvendiZ3BmeHh6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0MjgxNDYsImV4cCI6MjA1OTAwNDE0Nn0.ndW5aFWhFdb5l5XUElSRo8jCnuKuA5xf8H4wtDg65zg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
